name: taskapp
description: "Task App"

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ###### ================ UI ================= ######
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_svg: ^2.0.9
  lottie: ^2.7.0

  ###### ================ DATA SOURCE ================= ######
  dio: ^5.3.3
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

  # -------- App Icon Launcher ----------#
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo/app_logo.png"
  remove_alpha_ios: true

flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/lang/
    - assets/fonts/
    - assets/animations/